# Changes here will be overwritten by Copier
_commit: 1.5.7
_src_path: gh:pawamoy/copier-uv
author_email: pawamoy@pm.me
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2023'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: pawamoy@pm.me
copyright_license: ISC License
insiders: false
project_description: Griffe extension for PEP 727 – Documentation Metadata in Typing.
project_name: Griffe TypingDoc
python_package_command_line_name: ''
python_package_distribution_name: griffe-typingdoc
python_package_import_name: griffe_typingdoc
repository_name: griffe-typingdoc
repository_namespace: mkdocstrings
repository_provider: github.com

